# Generated by Django 5.0.1 on 2024-01-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="productinfo",
            new_name="product_Info",
        ),
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
